goorm-debug-alss/petclinic

build.gradle, src/main/java/org/springframework/samples/petclinic/domain/appointment/controller/AppointmentController.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentResponseDto.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/garbage/GarbagePetRepository.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/garbage/GarbageVetRepository.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/model/Appointment.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/repository/AppointmentRepository.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java, src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java
- Appointment 엔티티 리팩토링 및 코드 개선
- Swagger 의존성 추가 및 의존성 주석, 정렬
- 임시 GarbagePetRepository, GarbageVetRepository 추가 (바로 삭제 예정)
- 예약 생성 서비스 테스트 코드 추가
- 예약 생성 기능 구현
- close #7
=> feat : 예약 생성 API 구현

src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentResponseDto.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/Result.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/StatusCode.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java, src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java
- API 응답에 사용될 Result 클래스 및 상태코드를 관리하는 StatusCode 클래스 추가
- 예약 생성 로직을 명확하게 리팩토링
- API 요청 및 응답 명세에 맞게 수정
- close #12
=> refactor : 예약 생성 API 리팩토링

src/main/java/org/springframework/samples/petclinic/domain/vet/VetRepository.java, src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java, src/main/java/org/springframework/samples/petclinic/domain/vet/model/Vet.java, src/main/java/org/springframework/samples/petclinic/domain/vet/model/VetSpecialty.java, src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
- 특정 수의사 조회 기능 추가
- 전체 수의사 조회 기능 추가
- API 명세 업데이트
- close
=> feat: 수의사 조회 기능 추가(#8)

src/main/java/org/springframework/samples/petclinic/domain/vet/VetSpecialityRepository.java, src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java, src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
- 수의사 수정 및 삭제기능 구현
- API 명세 업데이트
- close
=> feat: 수의사 수정 / 삭제 기능 구현 (#21)

src/main/java/org/springframework/samples/petclinic/domain/appointment/controller/AppointmentController.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/model/Appointment.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/repository/AppointmentRepository.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentDeleteService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentReadService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java, src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java, src/test/java/domain/appointment/service/AppointmentDeleteServiceTest.java, src/test/java/domain/appointment/service/AppointmentReadServiceTest.java, src/test/java/domain/appointment/service/AppointmentUpdateServiceTest.java
- 예약 수정 / 삭제 기능을 구현했습니다.
- AppointmentRepository Long -> Integer로 변경후 사용 코드들 수정
- 테스트 작성
- close #24
=> feat : 예약 수정 / 삭제 API 기능 추가(#24)

src/main/java/org/springframework/samples/petclinic/domain/vet/VetRepository.java, src/main/java/org/springframework/samples/petclinic/domain/vet/VetSpecialityRepository.java, src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java, src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
- 전문분야 ID를 이용한 분야별 수의사 조회 기능 추가
- 전체 조회 엔드포인트 변경
- API 명세 업데이트
- close
=> feat: 분야별 수의사 조회 기능 추가 (#25)

src/main/java/org/springframework/samples/petclinic/domain/visit/VisitController.java, src/main/java/org/springframework/samples/petclinic/domain/visit/controller/VisitController.java, src/main/java/org/springframework/samples/petclinic/domain/visit/dto/VisitRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/visit/dto/VisitResponseDto.java, src/main/java/org/springframework/samples/petclinic/domain/visit/enums/StatusCode.java, src/main/java/org/springframework/samples/petclinic/domain/visit/model/Visit.java, src/main/java/org/springframework/samples/petclinic/domain/visit/repository/VisitRepository.java, src/main/java/org/springframework/samples/petclinic/domain/visit/service/VisitService.java, src/main/java/org/springframework/samples/petclinic/domain/visit/tempRepository/TempPetRepository.java
- 방문내역 생성 API 구현
- 특정 반려동물의 방문 내역 전체 조회 기능 추가
- close
=> feat: 방문내역 생성, 조회 API 기능 추가

src/main/java/org/springframework/samples/petclinic/domain/owner/controller/OwnerController.java, src/main/java/org/springframework/samples/petclinic/domain/owner/dto/UpdatePasswordRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/owner/dto/UpdateProfileRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/owner/repository/OwnerRepository.java, src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerService.java
- 주인 정보 수정 API를 추가하였습니다.
- 비밀번호 변경 API를 추가하였습니다.
- close #28
=> feat: 주인 정보 수정 API 추가

src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentResponseDto.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/model/Appointment.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentReadService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java, src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java, src/test/java/domain/appointment/service/AppointmentReadServiceTest.java, src/test/java/domain/appointment/service/AppointmentUpdateServiceTest.java
- 영향 받는 클래스들 리팩토링 작업완료
- LocalDate -> LocalDateTime으로 변경후 리팩토링 하였습니다.
- close #33
=> refactor : 예약 날짜 LocalDate -> LocalDateTime으로 변경(#33)

src/main/java/org/springframework/samples/petclinic/domain/appointment/garbage/GarbagePetRepository.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/garbage/GarbageVetRepository.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java, src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java, src/test/java/domain/appointment/service/AppointmentUpdateServiceTest.java
- GarbagePetRepository -> PetRepository
- GarbageVetRepository -> VetRepository
- Garbage 패키지에 테스트용 Repository 삭제후 구현된 Repository로 변경후 리팩토링 하였습니다.
- close #44
=> refactor: 테스트용 Repository 삭제후 사용코드 리팩토링(#44)

src/main/java/org/springframework/samples/petclinic/domain/history/controller/HistoryController.java, src/main/java/org/springframework/samples/petclinic/domain/history/service/HistoryService.java
- 진료내역 수정 API 구현
- 진료내역 삭제 API 구현
- close
=> feat: 진료내역 수정/삭제 기능 구현(#51)

src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java, src/test/java/domain/appointment/service/VetControllerTest.java, src/test/java/domain/appointment/service/VetServiceTest.java
- VetController을 public으로 변경
- VetServiceTest 작성
- VetControllerTest 작성
- close #34
=> feat: 수의사 관련 테스트 코드 추가 (#34)

src/main/java/org/springframework/samples/petclinic/domain/vet/controller/dto/VetRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java, src/test/java/domain/appointment/service/VetServiceTest.java, src/test/java/domain/vet/controller/VetControllerTest.java, src/test/java/domain/vet/service/VetServiceTest.java
- VetService - Register에서 각각의 필드가 Null일 때 저장이 안되도록 처리
- close #56
=> feat: VetService Register 메서드 null 처리 (#56)

src/main/java/org/springframework/samples/petclinic/domain/appointment/controller/AppointmentController.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/mapper/AppointmentHelper.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentDeleteService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentReadService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java, src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java, src/test/java/domain/appointment/service/AppointmentDeleteServiceTest.java, src/test/java/domain/appointment/service/AppointmentReadServiceTest.java
- AppointmentHelper 추가 및 공통 메서드 추출
- Service 리팩토링
- Test 리팩토링
- 불필요한 주석 제거
- close (#57 )
=> refactor: 예약 API 리팩토링 및 수정(#57) 

src/main/java/org/springframework/samples/petclinic/domain/vet/VetRepository.java, src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java, src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java, src/test/java/domain/vet/controller/VetControllerTest.java, src/test/java/domain/vet/service/VetServiceTest.java
- Vet 삭제시 Vet-Speciality도 삭제
- Vet 삭제시 해당 수의사가 존재하는지 확인하는 조건 추가
- VetController에서 void -> ResponseEntity<Void>로 변경
- close
=> fix: Vet delete 디버깅 (#59)

src/main/java/org/springframework/samples/petclinic/domain/review/controller/ReviewController.java, src/main/java/org/springframework/samples/petclinic/domain/review/dto/Result.java, src/main/java/org/springframework/samples/petclinic/domain/review/dto/ReviewRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/review/dto/ReviewResponseDto.java, src/main/java/org/springframework/samples/petclinic/domain/review/dto/StatusCode.java, src/main/java/org/springframework/samples/petclinic/domain/review/exception/OwnerNotFoundException.java, src/main/java/org/springframework/samples/petclinic/domain/review/exception/ReviewNotFoundException.java, src/main/java/org/springframework/samples/petclinic/domain/review/exception/ReviewOwnershipException.java, src/main/java/org/springframework/samples/petclinic/domain/review/exception/VetNotFoundException.java, src/main/java/org/springframework/samples/petclinic/domain/review/mapper/ReviewHelper.java, src/main/java/org/springframework/samples/petclinic/domain/review/model/Review.java, src/main/java/org/springframework/samples/petclinic/domain/review/repository/ReviewRepository.java, src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewCreateService.java, src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewDeleteService.java, src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewReadService.java, src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewUpdateService.java, src/main/java/org/springframework/samples/petclinic/interceptor/AuthorizationInterceptor.java, src/test/java/domain/review/service/ReviewCreateServiceTest.java, src/test/java/domain/review/service/ReviewDeleteServiceTest.java, src/test/java/domain/review/service/ReviewReadServiceTest.java, src/test/java/domain/review/service/ReviewUpdateServiceTest.java
- 후기 API 구현 및 테스트 작성
- 토큰 헤더 authorization-token -> Authorization으로 변경 (오류 발생시 수정하겠습니다)
- close #61
=> feat: 후기 기능 API 기능 구현 및 테스트 작성

src/main/java/org/springframework/samples/petclinic/domain/review/controller/ReviewController.java, src/main/java/org/springframework/samples/petclinic/domain/review/exception/InvalidContentException.java, src/main/java/org/springframework/samples/petclinic/domain/review/exception/InvalidScoreException.java, src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewCreateService.java, src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewReadService.java, src/main/java/org/springframework/samples/petclinic/domain/vet/model/Vet.java, src/test/java/domain/review/service/ReviewCreateServiceTest.java, src/test/java/domain/review/service/ReviewReadServiceTest.java
- 리뷰 조회, 생성 서비스 예외처리 구현
- 테스트 케이스 추가
- close #66
=> feat: 예약 API 테스트 케이스 추가 및 수정(#66)

src/main/java/org/springframework/samples/petclinic/domain/visit/controller/VisitController.java, src/main/java/org/springframework/samples/petclinic/domain/visit/dto/VisitRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/visit/dto/VisitResponseDto.java, src/test/java/domain/visit/controller/VisitControllerTest.java, src/test/java/domain/visit/service/VisitServiceTest.java
- 방문 생성 테스트코드 작성
- 방문 조회 테스트코드 작성
- VisitResponseDto 수정
- close
=> feat: 방문 생성,조회 API 테스트코드 작성(#68)

build.gradle, src/main/java/org/springframework/samples/petclinic/config/security/JwtAuthenticationFilter.java, src/main/java/org/springframework/samples/petclinic/config/security/SecurityConfig.java, src/main/java/org/springframework/samples/petclinic/config/security/TokenBasedAuthentication.java, src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerAuthService.java, src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerProfileService.java
- 로그인, 비밀번호 업데이트 로직 수정
- Spring Security 의존성을 추가하여 보안 강화
- JWT 토큰 인증 로직을 추가하여 API 인증 처리
- 비밀번호를 BCrypt로 암호화하도록 회원가입 및 비밀번호 업데이트 로직 수정
- close #72
=> feat: 비밀번호 암호화 구현(#72)

src/main/java/org/springframework/samples/petclinic/config/security/JwtAuthenticationFilter.java, src/main/java/org/springframework/samples/petclinic/domain/owner/controller/OwnerController.java, src/main/java/org/springframework/samples/petclinic/domain/owner/service/BlacklistService.java, src/main/java/org/springframework/samples/petclinic/domain/token/service/TokenService.java
- 로그아웃 기능 구현
- 로그아웃된 토큰 정보는 블랙리스트에 추가
- close #74
=> feat: 로그아웃 기능 구현(#74)

src/test/java/domain/owner/service/BlacklistServiceTest.java, src/test/java/domain/owner/service/OwnerAuthServiceTest.java, src/test/java/domain/owner/service/OwnerProfileServiceTest.java, src/test/java/domain/owner/service/OwnerReadServiceTest.java, src/test/java/domain/token/service/TokenServiceTest.java
- 주인 API 테스트 구현
- 일단 서비스코드 기본만 구현해놓고 더 추가하겠습니다!
- close #76
=> feat: 주인 서비스, 토큰 서비스 테스트 구현(#76)

src/main/java/org/springframework/samples/petclinic/domain/appointment/controller/AppointmentController.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/exception/AppointmentNotFoundException.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/exception/PetNotFoundException.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/exception/VetNotFoundException.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/mapper/AppointmentHelper.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentDeleteService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentEntityRetrievalService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentReadService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java, src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java, src/test/java/domain/appointment/service/AppointmentDeleteServiceTest.java, src/test/java/domain/appointment/service/AppointmentReadServiceTest.java, src/test/java/domain/appointment/service/AppointmentUpdateServiceTest.java
- 주석 제거, 클래스명 변경, 메서드 추출 하였습니다
- close #91
=> refactor: 주석 제거, 클래스명 변경, 메서드 추출로 가독성 향상(#91)

src/main/java/org/springframework/samples/petclinic/domain/review/controller/ReviewController.java, src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewCreateService.java, src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewDeleteService.java, src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewEntityRetrievalService.java, src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewReadService.java, src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewUpdateService.java
- 주석 제거
- 메서드 추출하여 리팩토링
- close #92
=> refactor: 주석 제거 및 메소드 추출(#92)

src/test/java/domain/vet/controller/VetControllerTest.java, src/test/java/domain/vet/service/VetServiceTest.java
- WebMvcTest과 MockMvc를 이용하여 응답 및 동작하도록 리팩토링
- VetServiceTest에서 불필요한 메서드 삭제
- close #86
=> refactor: 수의사 controller 테스트 수정 (#86)

build.gradle, src/main/java/org/springframework/samples/petclinic/common/error/ErrorCodeInterface.java, src/main/java/org/springframework/samples/petclinic/common/error/VetErrorCode.java, src/main/java/org/springframework/samples/petclinic/common/exception/ApiException.java, src/main/java/org/springframework/samples/petclinic/common/exception/ApiExceptionInterface.java, src/main/java/org/springframework/samples/petclinic/common/result/ErrorResult.java, src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java, src/main/java/org/springframework/samples/petclinic/handler/GlobalExceptionHandler.java
- ErrorCodeInterface, ApiException, ApiExceptionInterface, ErrorResult, GlobalExceptionHandler 구현
- 예외처리 예시로 VetErrorCode 구현 후 VetService에 적용
- 기존 버전 오류로 `build.gradle` - Swagger Ui 버전 2.1.0 -> 2.7.0 변경
- close #99
=> feat: ExceptionHandler 구현 (#99)

src/main/java/org/springframework/samples/petclinic/common/error/VetErrorCode.java, src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java, src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
- VetErrorCode 추가
- 기존 코드에서 커스텀예외를 사용하도록 VetService 수정
- close #102
=> feat: Vet 관련 CustomException 처리 (#102)

src/main/java/org/springframework/samples/petclinic/common/error/VisitErrorCode.java, src/main/java/org/springframework/samples/petclinic/domain/visit/controller/VisitController.java, src/main/java/org/springframework/samples/petclinic/domain/visit/dto/VisitResponseDto.java, src/main/java/org/springframework/samples/petclinic/domain/visit/service/VisitService.java, src/test/java/domain/visit/controller/VisitControllerTest.java, src/test/java/domain/visit/service/VisitServiceTest.java
- VisitErrorCode 작성
- VisitService 및 VisitResponseDto 수정
- 테스트코드 수정
- API 명세 수정
- close
=> refactor: 방문 관련 API 응답 수정 및 리팩토링(#105)

src/main/java/org/springframework/samples/petclinic/common/error/HistoryErrorCode.java, src/main/java/org/springframework/samples/petclinic/domain/history/controller/HistoryController.java, src/main/java/org/springframework/samples/petclinic/domain/history/dto/HistoryResponseDto.java, src/main/java/org/springframework/samples/petclinic/domain/history/service/HistoryService.java, src/test/java/domain/history/controller/HistoryControllerTest.java, src/test/java/domain/history/service/HistoryServiceTest.java, src/test/java/domain/visit/service/VisitServiceTest.java
- HistoryErrorCode 작성
- HistoryService 및 HistoryResponseDto 수정
- 테스트코드 수정
- API 명세 수정
- close
=> refactor: 방문 관련 API 응답 수정 및 리팩토링(#106)

src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java, src/main/resources/application-test.properties, src/main/resources/db/mysql/data.sql, src/main/resources/db/mysql/schema.sql, src/test/java/domain/vet/service/VetServiceIntegrationTest.java, src/test/java/domain/vet/service/VetServiceTest.java
- data.sql, schema.sql 작성
- VetIntegrationService 구현
- application-test.properties 작성
- close #113
=> feat: vet 통합 테스트 구현 (#113)

src/main/java/org/springframework/samples/petclinic/common/error/OwnerErrorCode.java, src/main/java/org/springframework/samples/petclinic/domain/owner/controller/OwnerController.java, src/main/java/org/springframework/samples/petclinic/domain/owner/dto/LoginRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/owner/dto/OwnerResponseDto.java, src/main/java/org/springframework/samples/petclinic/domain/owner/dto/RegisterRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/owner/dto/UpdatePasswordRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/owner/dto/UpdateProfileRequestDto.java, src/main/java/org/springframework/samples/petclinic/domain/owner/mapper/OwnerMapper.java, src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerAuthService.java, src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerProfileService.java, src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerReadService.java, src/test/java/domain/appointment/controller/AppointmentControllerTest.java, src/test/java/domain/owner/controller/OwnerControllerTest.java, src/test/java/domain/owner/service/OwnerAuthServiceTest.java, src/test/java/domain/owner/service/OwnerProfileServiceTest.java, src/test/java/domain/owner/service/OwnerReadServiceTest.java
- 통합테스트 작성 및 서비스 코드들 리팩토링 했습니당
- close #111
=> refactor: 주인 API 리팩토링(#111)

src/test/java/domain/vet/controller/VetControllerTest.java
- VetController 단위테스트 -> 통합테스트로 수정
- close #127
=> refactor: VetControllerTest 수정 (#127)

README.md
- 개선하거나 추가할 부분 편하게 의견 주세요~~
- close #126
=> docs: 프로젝트 README.md 작성(#126)

build.gradle
- build.gradle에서 AOT 관련 플러그인 주석 처리하여 오류 해결
- close #130
=> fix: 배포 빌드시 ProcessAOT 오류가 발생하여 build.gradle에서 AOT 관련 플러그인 주석 처리하여 오류 해결

src/main/java/org/springframework/samples/petclinic/domain/review/service/DeleteReviewService.java
- 리뷰 삭제시 수의사 평점 및 리뷰 수 업데이트 코드 추가
- close
=> debug: 리뷰 삭제시 수의사 평점, 리뷰 수 반영 안되는 버그 수정(#137)

src/main/java/org/springframework/samples/petclinic/domain/appointment/service/CreateAppointmentService.java, src/main/java/org/springframework/samples/petclinic/domain/appointment/service/UpdateAppointmentService.java, src/main/java/org/springframework/samples/petclinic/domain/history/repository/HistoryRepository.java, src/main/java/org/springframework/samples/petclinic/domain/history/service/HistoryService.java, src/main/java/org/springframework/samples/petclinic/domain/pet/enums/PetStatus.java, src/main/java/org/springframework/samples/petclinic/domain/pet/mapper/PetMapper.java, src/main/java/org/springframework/samples/petclinic/domain/pet/model/Pet.java, src/main/java/org/springframework/samples/petclinic/domain/pet/repository/PetRepository.java, src/main/java/org/springframework/samples/petclinic/domain/pet/service/PetService.java, src/main/java/org/springframework/samples/petclinic/domain/vet/model/Vet.java, src/main/java/org/springframework/samples/petclinic/domain/visit/service/VisitService.java, src/main/resources/application.properties, src/main/resources/db/mysql/data.sql, src/main/resources/db/mysql/schema.sql, src/test/java/domain/appointment/service/CreateAppointmentServiceTest.java, src/test/java/domain/history/service/HistoryServiceIntegrationTest.java, src/test/java/domain/history/service/HistoryServiceTest.java, src/test/java/domain/owner/controller/OwnerControllerTest.java, src/test/java/domain/pet/service/PetServiceTest.java, src/test/java/domain/review/controller/ReviewControllerTest.java, src/test/java/domain/review/service/DeleteReviewServiceTest.java, src/test/java/domain/review/service/ReadReviewServiceTest.java, src/test/java/domain/vet/controller/VetControllerTest.java, src/test/java/domain/vet/service/VetServiceTest.java, src/test/java/domain/visit/service/VisitServiceTest.java
- 등록 상태 enum 추가 및 DB 스키마 수정
- 관련 메서드 수정
- 테스트코드 리팩토링
- close
=> debug: Pet 삭제 시 관련 테이블로 인한 삭제 불가 수정(#139)
